# Generated by Django 6.0.3 on 2026-03-29 14:30

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userprofile'),
        ('naac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naaccriteria',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='naacmetric',
            options={'ordering': ['metric_code']},
        ),
        migrations.AlterModelOptions(
            name='naacmetricentry',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='naacmetricentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='naaccriteria',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='naaccriteria',
            name='weightage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='naacmetric',
            name='max_score',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='naacmetricentry',
            name='achieved_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='naacmetricentry',
            name='target_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='naacmetric',
            unique_together={('criteria', 'metric_code')},
        ),
        migrations.AddIndex(
            model_name='naacmetricentry',
            index=models.Index(fields=['year'], name='naac_naacme_year_2a8377_idx'),
        ),
    ]
