# Generated by Django 6.0.4 on 2026-04-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naac', '0002_alter_naaccriteria_options_alter_naacmetric_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naacmetric',
            name='template_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
