# Generated by Django 6.0.3 on 2026-03-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthealth',
            name='naac_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='departmenthealth',
            name='nba_score',
            field=models.FloatField(default=0),
        ),
    ]
