# Generated by Django 6.0.3 on 2026-03-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_departmenthealth_naac_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentrisk',
            name='naac_risk',
            field=models.CharField(default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='departmentrisk',
            name='nba_risk',
            field=models.CharField(default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='departmentrisk',
            name='risk_level',
            field=models.CharField(default='LOW', max_length=10),
        ),
    ]
