# Generated by Django 6.0.2 on 2026-03-08 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttainmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attainment', models.FloatField()),
                ('year', models.IntegerField()),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainment_entries', to='academics.courseoutcome')),
            ],
            options={
                'ordering': ['course_outcome'],
            },
        ),
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_outcomes', to='academics.program')),
            ],
            options={
                'ordering': ['program', 'code'],
                'unique_together': {('program', 'code')},
            },
        ),
        migrations.CreateModel(
            name='COPOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_strength', models.IntegerField(default=1)),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_mappings', to='academics.courseoutcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_mappings', to='nba.programoutcome')),
            ],
            options={
                'ordering': ['program_outcome'],
                'unique_together': {('course_outcome', 'program_outcome')},
            },
        ),
    ]
