# Generated by Django 6.0.4 on 2026-04-29 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_poattainment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBACriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NBAMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('template', models.FileField(blank=True, null=True, upload_to='nba/templates/')),
                ('filled_file', models.FileField(blank=True, null=True, upload_to='nba/uploads/')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='nba.nbacriteria')),
            ],
        ),
    ]
