# Generated by Django 6.0.4 on 2026-04-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0003_nbacriteria_nbametric'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbametric',
            name='template_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
