# Generated by Django 6.0.2 on 2026-06-21 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NIRFYearTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('tlr_target', models.FloatField(default=0)),
                ('rp_target', models.FloatField(default=0)),
                ('go_target', models.FloatField(default=0)),
                ('oi_target', models.FloatField(default=0)),
                ('pr_target', models.FloatField(default=0)),
                ('overall_target', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GOIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=300)),
                ('current_value', models.FloatField(default=0)),
                ('target_value', models.FloatField(default=0)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nirf.nirfyeartarget')),
            ],
        ),
        migrations.CreateModel(
            name='OIIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=300)),
                ('current_value', models.FloatField(default=0)),
                ('target_value', models.FloatField(default=0)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nirf.nirfyeartarget')),
            ],
        ),
        migrations.CreateModel(
            name='PRIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=300)),
                ('current_value', models.FloatField(default=0)),
                ('target_value', models.FloatField(default=0)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nirf.nirfyeartarget')),
            ],
        ),
        migrations.CreateModel(
            name='RPIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=300)),
                ('current_value', models.FloatField(default=0)),
                ('target_value', models.FloatField(default=0)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nirf.nirfyeartarget')),
            ],
        ),
        migrations.CreateModel(
            name='TLRIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=300)),
                ('current_value', models.FloatField(default=0)),
                ('target_value', models.FloatField(default=0)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nirf.nirfyeartarget')),
            ],
        ),
    ]
