# Generated by Django 6.0.2 on 2026-03-08 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('established_year', models.IntegerField()),
                ('intake', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('established_year', models.IntegerField()),
                ('naac_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('autonomous_status', models.BooleanField(default=False)),
                ('affiliated_university', models.CharField(blank=True, max_length=300, null=True)),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('is_phd', models.BooleanField(default=False)),
                ('experience_years', models.IntegerField(default=0)),
                ('research_publications', models.IntegerField(default=0)),
                ('patents', models.IntegerField(default=0)),
                ('funded_projects', models.IntegerField(default=0)),
                ('api_score', models.FloatField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='dashboard.department')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyPerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026)),
                ('academic_score', models.FloatField(default=0)),
                ('research_score', models.FloatField(default=0)),
                ('student_impact_score', models.FloatField(default=0)),
                ('responsibility_score', models.FloatField(default=0)),
                ('development_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to='dashboard.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dean_name', models.CharField(blank=True, max_length=200, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='dashboard.institution')),
            ],
        ),
        migrations.CreateModel(
            name='GovernanceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('campus_md', 'Campus MD'), ('campus_director', 'Campus Director'), ('campus_deputy_director', 'Campus Deputy Director'), ('admin', 'Admin'), ('school_dean', 'School Dean'), ('hod', 'Head of Department'), ('faculty', 'Faculty')], max_length=30)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='governance_role', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.school')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='dashboard.school'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year_of_admission', models.IntegerField()),
                ('current_year', models.IntegerField()),
                ('cgpa', models.FloatField(default=0)),
                ('placed', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='dashboard.department')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_students', to='dashboard.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cgpa', models.FloatField(default=0)),
                ('attendance', models.FloatField(default=0)),
                ('risk_level', models.CharField(default='Normal', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='dashboard.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='dashboard.student')),
            ],
        ),
    ]
