# Generated by Django 6.0.2 on 2026-07-25 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.institution'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.school'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('campus_md', 'Campus MD'), ('campus_director', 'Campus Director'), ('campus_deputy_director', 'Campus Deputy Director'), ('iqac_dean', 'IQAC Dean'), ('iqac_deputy_dean', 'IQAC Deputy Dean'), ('iqac_cell_head', 'IQAC Cell Head'), ('school_dean', 'School Dean'), ('school_principal', 'School Principal'), ('research_cell_head', 'Research Cell Head'), ('hod', 'Head of Department'), ('faculty', 'Faculty'), ('admin', 'System Administrator')], max_length=50),
        ),
    ]
