# Generated by Django 6.0.2 on 2026-06-21 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aireport',
            name='is_pdf_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aireport',
            name='is_word_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aireport',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('EDITED', 'Edited'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked'), ('PDF', 'PDF Generated'), ('WORD', 'Word Generated')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.aireport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
